# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Versão mais recente no momento da escrita
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
